### ISSUE TITLE
[Bug]: Shiba - GC counts as a movement, but it costs ~4 TU, not 2

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#87] opened 2023-01-27 21:46 UTC
### Contact Details

Simi#2465

### What happened?

If it is a movement, then the basic rule that a movement should cost no more than 2 TU is broken. 

### Steps to reproduce

Use GC and check the timeline.

### Expected Behavior

The maximum cost of a movement is 2 TU.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment] 2023-01-30 15:14
@kissiga GC is still considered an ability, despite being able to be used in place of a movement. For this reason, it still consumes 4TU as intended instead of the max 2TU a regular move would do instead. 

Closing out this issue as per my comment above.

**Closed by EvanxQA** 2023-01-30 15:14 UTC
Labels: bug, triage
