### ISSUE TITLE
[Bug]: N9 - SStrike effect removed after ~4 TU

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#84] opened 2023-01-27 21:14 UTC
### Contact Details

Simi#2465

### What happened?

SStrike effect removed after ~4 TU

### Steps to reproduce

Watch the video.

### Expected Behavior

SStrike effect stops after 8 TU.

### Screenshots / Videos capture / Attachments

https://user-images.githubusercontent.com/16439674/215201353-47508127-2685-4fad-ae8e-e6fccd92b2be.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment] 2023-01-30 15:05
@kissiga In your video above, only the snare appears to have lasted only 4TU (1 turn, as intended). The defense debuff is still active after the movement debuff is removed (lasts 8TU).

Closing out this ticket as per my comment.

**Closed by EvanxQA** 2023-01-30 15:05 UTC
Labels: bug, triage
