### ISSUE TITLE
[Bug]: Axo - Defensive Dome bug?  

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#101] opened 2023-01-30 21:48 UTC
### Contact Details

Simi

### What happened?

I activated a (2nd) Def. Dome which disappeared immediately on the next attack.

### Steps to reproduce

.

### Expected Behavior

I don't think it should have disappeared.
I got Sharp Gust attack (DD was activated) in the previous rounds, and it didn't disappear.

### Screenshots / Videos capture / Attachments

https://user-images.githubusercontent.com/16439674/215602255-f1f950f0-dedf-406f-8aae-861098404c4f.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment] 2023-01-31 16:32
Closing out this issue as a duplicate of #95. We will use that ticket to continue our investigation.

**Closed by EvanxQA** 2023-01-31 16:32 UTC
Labels: bug, triage, tactics
