### ISSUE TITLE
[Bug]: Jumpscare activates twice without pressing

### ISSUE THREAD

**Issue by Attis-Axo** [Aurory-Game/aurory-issues#98] opened 2023-01-29 19:29 UTC
### Contact Details

Attis#3587

### What happened?

A bug happened! Jumpscare activated twice on a single marked dipking, please see clip for more details!

https://clips.twitch.tv/CorrectRepleteBottlePJSugar-Qo6gCtMwPZHReXSK

### Steps to reproduce

Use jumpscare, and have enough have to have it for 2 goes (it should remove marking after first use)

### Expected Behavior

To remove mark after first use and have to fly over again which did not happen

### Which browsers are you seeing the problem on?

Chrome, Brave

### Which wallet are you using?

No wallet

### Screenshots / Videos capture / Attachments

https://clips.twitch.tv/CorrectRepleteBottlePJSugar-Qo6gCtMwPZHReXSK is the video capture for this (attached above)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment] 2023-01-30 22:54
Closing out as duplicate of #65

**Closed by EvanxQA** 2023-01-30 22:54 UTC
Labels: bug, triage
